<a href="https://colab.research.google.com/github/NATHAN-70/AI-ML/blob/main/boosting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/personality_datasert.csv')

In [ ]:
df.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,4.0,No,4.0,6.0,No,13.0,5.0,Extrovert
1,9.0,Yes,0.0,0.0,Yes,0.0,3.0,Introvert
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert
3,0.0,No,6.0,7.0,No,14.0,8.0,Extrovert
4,3.0,No,9.0,4.0,No,8.0,5.0,Extrovert

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Time_spent_Alone           2900 non-null   float64
 1   Stage_fear                 2900 non-null   object
 2   Social_event_attendance    2900 non-null   float64
 3   Going_outside              2900 non-null   float64
 4   Drained_after_socializing  2900 non-null   object
 5   Friends_circle_size        2900 non-null   float64
 6   Post_frequency             2900 non-null   float64
 7   Personality                2900 non-null   object
dtypes: float64(5), object(3)
memory usage: 181.4+ KB

In [ ]:
df.isnull().sum()

Time_spent_Alone             0
Stage_fear                   0
Social_event_attendance      0
Going_outside                0
Drained_after_socializing    0
Friends_circle_size          0
Post_frequency               0
Personality                  0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Personality']=le.fit_transform(df['Personality'])
df['Drained_after_socializing']=le.fit_transform(df['Drained_after_socializing'])
df['Stage_fear']=le.fit_transform(df['Stage_fear'])
df

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,4.0,0,4.0,6.0,0,13.0,5.0,0
1,9.0,1,0.0,0.0,1,0.0,3.0,1
2,9.0,1,1.0,2.0,1,5.0,2.0,1
3,0.0,0,6.0,7.0,0,14.0,8.0,0
4,3.0,0,9.0,4.0,0,8.0,5.0,0
...,...,...,...,...,...,...,...,...
2895,3.0,0,7.0,6.0,0,6.0,6.0,0
2896,3.0,0,8.0,3.0,0,14.0,9.0,0
2897,4.0,1,1.0,1.0,1,4.0,0.0,1
2898,11.0,1,1.0,3.0,1,2.0,0.0,1
2899,3.0,0,6.0,6.0,0,6.0,9.0,0

In [ ]:
x=df.drop(('Personality'),axis=1)
y=df['Personality']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score
model=AdaBoostClassifier()
model.fit(x_train,y_train)

AdaBoostClassifier()

In [ ]:
y_pred=model.predict(x_test)
print ("Accuracy",accuracy_score(y_test,y_pred))

Accuracy 0.9241379310344827

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
model=GradientBoostingClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print ("Accuracy",accuracy_score(y_test,y_pred))

Accuracy 0.9293103448275862

In [ ]:
from xgboost import XGBClassifier
model=XGBClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print ("Accuracy",accuracy_score(y_test,y_pred))

Accuracy 0.9172413793103448

In [ ]:
from lightgbm import LGBMClassifier
model=LGBMClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print ("Accuracy",accuracy_score(y_test,y_pred))

[LightGBM] [Info] Number of positive: 1131, number of negative: 1189
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000553 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 66
[LightGBM] [Info] Number of data points in the train set: 2320, number of used features: 7
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.487500 -> initscore=-0.050010
[LightGBM] [Info] Start training from score -0.050010
Accuracy 0.9189655172413793

In [ ]:
!pip install catboost
from catboost import CatBoostClassifier
model=CatBoostClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print ("Accuracy",accuracy_score(y_test,y_pred))

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.9 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10
Learning rate set to 0.014757
0:	learn: 0.6761250	total: 48.6ms	remaining: 48.6s
1:	learn: 0.6596602	total: 49.6ms	remaining: 24.7s
2:	learn: 0.6424619	total: 50.4ms	remaining: 16.8s
3:	learn: 0.6267332	total: 51.2ms	remaining: 12.7s
4:	learn: 0.6117114	total: 52ms	remaining: 10.3s
5:	learn: 0.5959271	total: 52.8ms	remaining: 8.74s
6:	learn: 0.5823967	total: 53.5ms	remaining: 7.59s
7:	learn: 0.5684613	total: 54.4ms	remaining: 6.74s
8:	learn: 0.5544424	total: 55.2ms	remaining: 6.08s
9:	learn: 0.5425668	total: 56.1ms	remaining: 5.55s
10:	learn: 0.5310583	total: 56.8ms	remaining: 5.1s
11:	learn: 0.5188579	total: 57.6ms	remaining: 4.74s
12:	learn: 0.5072186	total: 58.3ms	remaining: 4.43s
13:	learn: 0.4965509	total: 59.1ms	remaining: 4.17s
14:	learn: 0.4865125	total: 59.9ms	remaining: 3.93s
15:	learn: 0.4760439	total: 60.7ms	remaining: 3.73s
16:	learn: 0.4662008	total: 61.5ms	remaining: 3.56s
17:	learn: 0.4574738	total: 62.3ms	remaining: 3.4s
18:	learn: 0.4490634	total: 63.1ms	remaining: 3.26s
19:	learn: 0.4409148	total: 63.9ms	remaining: 3.13s
20:	learn: 0.4338235	total: 64.5ms	remaining: 3.01s
21:	learn: 0.4257885	total: 65.3ms	remaining: 2.9s
22:	learn: 0.4184831	total: 66ms	remaining: 2.81s
23:	learn: 0.4110392	total: 66.9ms	remaining: 2.72s
24:	learn: 0.4052414	total: 67.5ms	remaining: 2.63s
25:	learn: 0.3981241	total: 68.3ms	remaining: 2.56s
26:	learn: 0.3909744	total: 69.1ms	remaining: 2.49s
27:	learn: 0.3842220	total: 69.9ms	remaining: 2.43s
28:	learn: 0.3783651	total: 71.5ms	remaining: 2.39s
29:	learn: 0.3723671	total: 72.2ms	remaining: 2.33s
30:	learn: 0.3669313	total: 73.1ms	remaining: 2.29s
31:	learn: 0.3616050	total: 73.9ms	remaining: 2.24s
32:	learn: 0.3565256	total: 74.7ms	remaining: 2.19s
33:	learn: 0.3511883	total: 75.6ms	remaining: 2.15s
34:	learn: 0.3464012	total: 76.4ms	remaining: 2.11s
35:	learn: 0.3420375	total: 77.2ms	remaining: 2.07s
36:	learn: 0.3379074	total: 77.8ms	remaining: 2.03s
37:	learn: 0.3334256	total: 78.8ms	remaining: 1.99s
38:	learn: 0.3294930	total: 79.6ms	remaining: 1.96s
39:	learn: 0.3261183	total: 80.4ms	remaining: 1.93s
40:	learn: 0.3226335	total: 81.2ms	remaining: 1.9s
41:	learn: 0.3191020	total: 82ms	remaining: 1.87s
42:	learn: 0.3153421	total: 82.8ms	remaining: 1.84s
43:	learn: 0.3119754	total: 83.6ms	remaining: 1.81s
44:	learn: 0.3088911	total: 84.4ms	remaining: 1.79s
45:	learn: 0.3056638	total: 85.1ms	remaining: 1.76s
46:	learn: 0.3027318	total: 85.8ms	remaining: 1.74s
47:	learn: 0.3000247	total: 86.6ms	remaining: 1.72s
48:	learn: 0.2972754	total: 87.4ms	remaining: 1.7s
49:	learn: 0.2944279	total: 88.3ms	remaining: 1.68s
50:	learn: 0.2920406	total: 89.1ms	remaining: 1.66s
51:	learn: 0.2895037	total: 89.9ms	remaining: 1.64s
52:	learn: 0.2871744	total: 90.7ms	remaining: 1.62s
53:	learn: 0.2847268	total: 91.5ms	remaining: 1.6s
54:	learn: 0.2825970	total: 92.3ms	remaining: 1.59s
55:	learn: 0.2804514	total: 93.1ms	remaining: 1.57s
56:	learn: 0.2780761	total: 94ms	remaining: 1.55s
57:	learn: 0.2759259	total: 94.8ms	remaining: 1.54s
58:	learn: 0.2737246	total: 95.7ms	remaining: 1.53s
59:	learn: 0.2717258	total: 96.5ms	remaining: 1.51s
60:	learn: 0.2697181	total: 97.3ms	remaining: 1.5s
61:	learn: 0.2679912	total: 98.1ms	remaining: 1.48s
62:	learn: 0.2663201	total: 99ms	remaining: 1.47s
63:	learn: 0.2645132	total: 100ms	remaining: 1.46s
64:	learn: 0.2628634	total: 101ms	remaining: 1.45s
65:	learn: 0.2613971	total: 102ms	remaining: 1.44s
66:	learn: 0.2599588	total: 102ms	remaining: 1.43s
67:	learn: 0.2583830	total: 103ms	remaining: 1.42s
68:	learn: 0.2568268	total: 104ms	remaining: 1.4s
69:	learn: 0.2554071	total: 105ms	remaining: 1.39s
70:	learn: 0.2538476	total: 106ms	remaining: 1.38s
71:	learn: 0.2523641	total: 107ms	remaining: 1.37s
72:	learn: 0.2510365	total: 107ms	remaining: 1.36s
73:	learn: 0.2495492	total: 108ms	remaining: 1.35s
74:	learn: 0.2480931	total: 109ms	remaining: 1.34s
75:	learn: 0.2469488	total: 110ms	remaining: 1.34s
76:	learn: 0.2456520	total: 111ms	remaining: 1.33s
77:	learn: 0.2443429	total: 112ms	remaining: 1.32s
78:	learn: 0.2435264	total: 112ms	remaining: 1.31s
79:	learn: 0.2425389	total: 113ms	remaining: 1.3s
80:	learn: 0.2419375	total: 114ms	remaining: 1.29s
81:	learn: 0.2409804	total: 115ms	remaining: 1.28s
82:	learn: 0.2401399	total: 115ms	remaining: 1.27s
83:	learn: 0.2394831	total: 116ms	remaining: 1.27s
84:	learn: 0.2387570	total: 117ms	remaining: 1.26s
85:	learn: 0.2380772	total: 118ms	remaining: 1.25s
86:	learn: 0.2373277	total: 119ms	remaining: 1.24s
87:	learn: 0.2366167	total: 119ms	remaining: 1.24s
88:	learn: 0.2361304	total: 120ms	remaining: 1.23s
89:	learn: 0.2352378	total: 121ms	remaining: 1.22s
90:	learn: 0.2344529	total: 122ms	remaining: 1.22s
91:	learn: 0.2337923	total: 123ms	remaining: 1.21s
92:	learn: 0.2332618	total: 124ms	remaining: 1.21s
93:	learn: 0.2325427	total: 125ms	remaining: 1.2s
94:	learn: 0.2320228	total: 125ms	remaining: 1.19s
95:	learn: 0.2312079	total: 126ms	remaining: 1.19s
96:	learn: 0.2306041	total: 127ms	remaining: 1.18s
97:	learn: 0.2296890	total: 128ms	remaining: 1.18s
98:	learn: 0.2290147	total: 129ms	remaining: 1.17s
99:	learn: 0.2285237	total: 130ms	remaining: 1.17s
100:	learn: 0.2280078	total: 131ms	remaining: 1.17s
101:	learn: 0.2274715	total: 132ms	remaining: 1.16s
102:	learn: 0.2268736	total: 133ms	remaining: 1.16s
103:	learn: 0.2263873	total: 134ms	remaining: 1.16s
104:	learn: 0.2259182	total: 135ms	remaining: 1.15s
105:	learn: 0.2252561	total: 136ms	remaining: 1.14s
106:	learn: 0.2247523	total: 137ms	remaining: 1.14s
107:	learn: 0.2243884	total: 137ms	remaining: 1.13s
108:	learn: 0.2238951	total: 138ms	remaining: 1.13s
109:	learn: 0.2236838	total: 139ms	remaining: 1.12s
110:	learn: 0.2231810	total: 140ms	remaining: 1.12s
111:	learn: 0.2226807	total: 140ms	remaining: 1.11s
112:	learn: 0.2223161	total: 141ms	remaining: 1.11s
113:	learn: 0.2220274	total: 142ms	remaining: 1.1s
114:	learn: 0.2214531	total: 143ms	remaining: 1.1s
115:	learn: 0.2210522	total: 144ms	remaining: 1.09s
116:	learn: 0.2206799	total: 144ms	remaining: 1.09s
117:	learn: 0.2200664	total: 145ms	remaining: 1.09s
118:	learn: 0.2196958	total: 146ms	remaining: 1.08s
119:	learn: 0.2193132	total: 147ms	remaining: 1.08s
120:	learn: 0.2189334	total: 148ms	remaining: 1.07s
121:	learn: 0.2185252	total: 149ms	remaining: 1.07s
122:	learn: 0.2181564	total: 149ms	remaining: 1.06s
123:	learn: 0.2178432	total: 150ms	remaining: 1.06s
124:	learn: 0.2171897	total: 151ms	remaining: 1.06s
125:	learn: 0.2169123	total: 152ms	remaining: 1.05s
126:	learn: 0.2165954	total: 153ms	remaining: 1.05s
127:	learn: 0.2163204	total: 154ms	remaining: 1.04s
128:	learn: 0.2160112	total: 154ms	remaining: 1.04s
129:	learn: 0.2158091	total: 155ms	remaining: 1.04s
130:	learn: 0.2155282	total: 156ms	remaining: 1.03s
131:	learn: 0.2152867	total: 157ms	remaining: 1.03s
132:	learn: 0.2150337	total: 158ms	remaining: 1.03s
133:	learn: 0.2148448	total: 159ms	remaining: 1.02s
134:	learn: 0.2146183	total: 159ms	remaining: 1.02s
135:	learn: 0.2145425	total: 160ms	remaining: 1.02s
136:	learn: 0.2143231	total: 161ms	remaining: 1.01s
137:	learn: 0.2140030	total: 162ms	remaining: 1.01s
138:	learn: 0.2137991	total: 162ms	remaining: 1s
139:	learn: 0.2135090	total: 163ms	remaining: 1s
140:	learn: 0.2131666	total: 164ms	remaining: 999ms
141:	learn: 0.2129459	total: 165ms	remaining: 996ms
142:	learn: 0.2127441	total: 166ms	remaining: 993ms
143:	learn: 0.2126239	total: 167ms	remaining: 990ms
144:	learn: 0.2124843	total: 167ms	remaining: 986ms
145:	learn: 0.2123031	total: 168ms	remaining: 983ms
146:	learn: 0.2121269	total: 169ms	remaining: 980ms
147:	learn: 0.2116556	total: 170ms	remaining: 977ms
148:	learn: 0.2114623	total: 170ms	remaining: 974ms
149:	learn: 0.2112079	total: 171ms	remaining: 970ms
150:	learn: 0.2108955	total: 172ms	remaining: 967ms
151:	learn: 0.2106150	total: 173ms	remaining: 964ms
152:	learn: 0.2104589	total: 174ms	remaining: 961ms
153:	learn: 0.2100903	total: 174ms	remaining: 958ms
154:	learn: 0.2100210	total: 175ms	remaining: 955ms
155:	learn: 0.2098554	total: 176ms	remaining: 952ms
156:	learn: 0.2097400	total: 177ms	remaining: 948ms
157:	learn: 0.2095078	total: 177ms	remaining: 945ms
158:	learn: 0.2093472	total: 178ms	remaining: 942ms
159:	learn: 0.2091508	total: 179ms	remaining: 940ms
160:	learn: 0.2089432	total: 180ms	remaining: 937ms
161:	learn: 0.2086073	total: 181ms	remaining: 934ms
162:	learn: 0.2084625	total: 181ms	remaining: 931ms
163:	learn: 0.2082228	total: 182ms	remaining: 929ms
164:	learn: 0.2080090	total: 183ms	remaining: 926ms
165:	learn: 0.2078063	total: 184ms	remaining: 923ms
166:	learn: 0.2075876	total: 185ms	remaining: 921ms
167:	learn: 0.2075520	total: 185ms	remaining: 917ms
168:	learn: 0.2073692	total: 186ms	remaining: 915ms
169:	learn: 0.2071399	total: 187ms	remaining: 912ms
170:	learn: 0.2068948	total: 188ms	remaining: 910ms
171:	learn: 0.2066914	total: 189ms	remaining: 908ms
172:	learn: 0.2063763	total: 189ms	remaining: 906ms
173:	learn: 0.2062200	total: 190ms	remaining: 904ms
174:	learn: 0.2061345	total: 192ms	remaining: 905ms
175:	learn: 0.2059007	total: 193ms	remaining: 902ms
176:	learn: 0.2057218	total: 194ms	remaining: 903ms
177:	learn: 0.2055270	total: 195ms	remaining: 902ms
178:	learn: 0.2052968	total: 197ms	remaining: 906ms
179:	learn: 0.2051804	total: 199ms	remaining: 906ms
180:	learn: 0.2049867	total: 200ms	remaining: 906ms
181:	learn: 0.2048144	total: 201ms	remaining: 904ms
182:	learn: 0.2046911	total: 202ms	remaining: 902ms
183:	learn: 0.2045802	total: 203ms	remaining: 900ms
184:	learn: 0.2043750	total: 204ms	remaining: 897ms
185:	learn: 0.2042267	total: 205ms	remaining: 895ms
186:	learn: 0.2039721	total: 205ms	remaining: 893ms
187:	learn: 0.2037934	total: 206ms	remaining: 891ms
188:	learn: 0.2037100	total: 207ms	remaining: 889ms
189:	learn: 0.2035530	total: 208ms	remaining: 886ms
190:	learn: 0.2034776	total: 209ms	remaining: 884ms
191:	learn: 0.2033069	total: 210ms	remaining: 882ms
192:	learn: 0.2030791	total: 210ms	remaining: 880ms
193:	learn: 0.2029019	total: 211ms	remaining: 877ms
194:	learn: 0.2026865	total: 212ms	remaining: 875ms
195:	learn: 0.2025789	total: 213ms	remaining: 873ms
196:	learn: 0.2024119	total: 214ms	remaining: 871ms
197:	learn: 0.2022441	total: 214ms	remaining: 869ms
198:	learn: 0.2020550	total: 215ms	remaining: 866ms
199:	learn: 0.2018549	total: 216ms	remaining: 864ms
200:	learn: 0.2017171	total: 217ms	remaining: 862ms
201:	learn: 0.2015561	total: 218ms	remaining: 860ms
202:	learn: 0.2013614	total: 218ms	remaining: 858ms
203:	learn: 0.2011576	total: 219ms	remaining: 856ms
204:	learn: 0.2010720	total: 220ms	remaining: 853ms
205:	learn: 0.2008629	total: 221ms	remaining: 851ms
206:	learn: 0.2005896	total: 222ms	remaining: 849ms
207:	learn: 0.2003787	total: 222ms	remaining: 847ms
208:	learn: 0.2001861	total: 223ms	remaining: 845ms
209:	learn: 0.2000122	total: 224ms	remaining: 843ms
210:	learn: 0.1999694	total: 225ms	remaining: 841ms
211:	learn: 0.1998941	total: 226ms	remaining: 839ms
212:	learn: 0.1997444	total: 226ms	remaining: 836ms
213:	learn: 0.1996592	total: 227ms	remaining: 835ms
214:	learn: 0.1994425	total: 228ms	remaining: 832ms
215:	learn: 0.1992928	total: 229ms	remaining: 830ms
216:	learn: 0.1991471	total: 230ms	remaining: 829ms
217:	learn: 0.1989374	total: 230ms	remaining: 827ms
218:	learn: 0.1987524	total: 231ms	remaining: 825ms
219:	learn: 0.1986559	total: 232ms	remaining: 823ms
220:	learn: 0.1984048	total: 233ms	remaining: 821ms
221:	learn: 0.1982643	total: 234ms	remaining: 819ms
222:	learn: 0.1980650	total: 234ms	remaining: 817ms
223:	learn: 0.1980112	total: 235ms	remaining: 814ms
224:	learn: 0.1978966	total: 236ms	remaining: 812ms
225:	learn: 0.1977990	total: 237ms	remaining: 811ms
226:	learn: 0.1977087	total: 237ms	remaining: 809ms
227:	learn: 0.1975510	total: 238ms	remaining: 807ms
228:	learn: 0.1974406	total: 239ms	remaining: 805ms
229:	learn: 0.1972226	total: 240ms	remaining: 803ms
230:	learn: 0.1970220	total: 241ms	remaining: 802ms
231:	learn: 0.1968804	total: 242ms	remaining: 800ms
232:	learn: 0.1966835	total: 242ms	remaining: 798ms
233:	learn: 0.1965819	total: 243ms	remaining: 796ms
234:	learn: 0.1964603	total: 244ms	remaining: 795ms
235:	learn: 0.1963222	total: 245ms	remaining: 793ms
236:	learn: 0.1962085	total: 246ms	remaining: 791ms
237:	learn: 0.1960655	total: 247ms	remaining: 790ms
238:	learn: 0.1958892	total: 248ms	remaining: 788ms
239:	learn: 0.1956842	total: 248ms	remaining: 787ms
240:	learn: 0.1954401	total: 249ms	remaining: 785ms
241:	learn: 0.1953656	total: 250ms	remaining: 783ms
242:	learn: 0.1951811	total: 251ms	remaining: 781ms
243:	learn: 0.1950167	total: 252ms	remaining: 780ms
244:	learn: 0.1949183	total: 252ms	remaining: 778ms
245:	learn: 0.1947377	total: 253ms	remaining: 776ms
246:	learn: 0.1945325	total: 254ms	remaining: 775ms
247:	learn: 0.1943896	total: 255ms	remaining: 773ms
248:	learn: 0.1941668	total: 256ms	remaining: 771ms
249:	learn: 0.1939976	total: 257ms	remaining: 770ms
250:	learn: 0.1939311	total: 257ms	remaining: 768ms
251:	learn: 0.1937860	total: 258ms	remaining: 766ms
252:	learn: 0.1936835	total: 259ms	remaining: 765ms
253:	learn: 0.1935422	total: 260ms	remaining: 763ms
254:	learn: 0.1934566	total: 261ms	remaining: 761ms
255:	learn: 0.1933255	total: 261ms	remaining: 760ms
256:	learn: 0.1932961	total: 262ms	remaining: 758ms
257:	learn: 0.1931855	total: 263ms	remaining: 756ms
258:	learn: 0.1930944	total: 264ms	remaining: 755ms
259:	learn: 0.1930035	total: 265ms	remaining: 753ms
260:	learn: 0.1928250	total: 265ms	remaining: 752ms
261:	learn: 0.1926858	total: 266ms	remaining: 750ms
262:	learn: 0.1926305	total: 267ms	remaining: 748ms
263:	learn: 0.1925144	total: 268ms	remaining: 747ms
264:	learn: 0.1924533	total: 269ms	remaining: 745ms
265:	learn: 0.1922329	total: 269ms	remaining: 743ms
266:	learn: 0.1921173	total: 270ms	remaining: 742ms
267:	learn: 0.1920272	total: 271ms	remaining: 740ms
268:	learn: 0.1918980	total: 272ms	remaining: 739ms
269:	learn: 0.1918046	total: 273ms	remaining: 737ms
270:	learn: 0.1917125	total: 273ms	remaining: 735ms
271:	learn: 0.1916024	total: 274ms	remaining: 734ms
272:	learn: 0.1915917	total: 275ms	remaining: 732ms
273:	learn: 0.1914637	total: 276ms	remaining: 730ms
274:	learn: 0.1913311	total: 276ms	remaining: 729ms
275:	learn: 0.1912697	total: 277ms	remaining: 727ms
276:	learn: 0.1911538	total: 278ms	remaining: 726ms
277:	learn: 0.1911351	total: 279ms	remaining: 724ms
278:	learn: 0.1909832	total: 279ms	remaining: 722ms
279:	learn: 0.1909245	total: 280ms	remaining: 720ms
280:	learn: 0.1907699	total: 281ms	remaining: 719ms
281:	learn: 0.1906581	total: 282ms	remaining: 717ms
282:	learn: 0.1905622	total: 283ms	remaining: 716ms
283:	learn: 0.1904145	total: 283ms	remaining: 714ms
284:	learn: 0.1903700	total: 284ms	remaining: 713ms
285:	learn: 0.1902752	total: 285ms	remaining: 711ms
286:	learn: 0.1901858	total: 286ms	remaining: 710ms
287:	learn: 0.1900638	total: 286ms	remaining: 708ms
288:	learn: 0.1899835	total: 287ms	remaining: 707ms
289:	learn: 0.1898445	total: 288ms	remaining: 705ms
290:	learn: 0.1897546	total: 289ms	remaining: 703ms
291:	learn: 0.1896483	total: 290ms	remaining: 702ms
292:	learn: 0.1895498	total: 290ms	remaining: 701ms
293:	learn: 0.1893935	total: 291ms	remaining: 699ms
294:	learn: 0.1892580	total: 292ms	remaining: 698ms
295:	learn: 0.1892177	total: 293ms	remaining: 696ms
296:	learn: 0.1891584	total: 294ms	remaining: 695ms
297:	learn: 0.1890779	total: 294ms	remaining: 694ms
298:	learn: 0.1889877	total: 295ms	remaining: 692ms
299:	learn: 0.1888926	total: 296ms	remaining: 691ms
300:	learn: 0.1888340	total: 297ms	remaining: 689ms
301:	learn: 0.1887402	total: 298ms	remaining: 688ms
302:	learn: 0.1885581	total: 298ms	remaining: 687ms
303:	learn: 0.1884123	total: 299ms	remaining: 685ms
304:	learn: 0.1882301	total: 300ms	remaining: 684ms
305:	learn: 0.1881833	total: 301ms	remaining: 682ms
306:	learn: 0.1881427	total: 302ms	remaining: 681ms
307:	learn: 0.1880702	total: 302ms	remaining: 679ms
308:	learn: 0.1879679	total: 303ms	remaining: 678ms
309:	learn: 0.1879568	total: 304ms	remaining: 676ms
310:	learn: 0.1878810	total: 305ms	remaining: 675ms
311:	learn: 0.1877906	total: 305ms	remaining: 673ms
312:	learn: 0.1876385	total: 306ms	remaining: 672ms
313:	learn: 0.1875767	total: 307ms	remaining: 671ms
314:	learn: 0.1874428	total: 308ms	remaining: 669ms
315:	learn: 0.1872671	total: 309ms	remaining: 668ms
316:	learn: 0.1872089	total: 309ms	remaining: 667ms
317:	learn: 0.1871503	total: 310ms	remaining: 665ms
318:	learn: 0.1870723	total: 311ms	remaining: 664ms
319:	learn: 0.1869822	total: 312ms	remaining: 663ms
320:	learn: 0.1868742	total: 313ms	remaining: 661ms
321:	learn: 0.1867643	total: 313ms	remaining: 660ms
322:	learn: 0.1867373	total: 314ms	remaining: 658ms
323:	learn: 0.1866164	total: 315ms	remaining: 657ms
324:	learn: 0.1865460	total: 316ms	remaining: 656ms
325:	learn: 0.1864304	total: 316ms	remaining: 654ms
326:	learn: 0.1863489	total: 317ms	remaining: 653ms
327:	learn: 0.1862572	total: 318ms	remaining: 652ms
328:	learn: 0.1860669	total: 319ms	remaining: 650ms
329:	learn: 0.1859595	total: 320ms	remaining: 649ms
330:	learn: 0.1858619	total: 321ms	remaining: 648ms
331:	learn: 0.1857463	total: 321ms	remaining: 647ms
332:	learn: 0.1857165	total: 322ms	remaining: 645ms
333:	learn: 0.1856890	total: 323ms	remaining: 644ms
334:	learn: 0.1855384	total: 324ms	remaining: 643ms
335:	learn: 0.1853750	total: 325ms	remaining: 641ms
336:	learn: 0.1852244	total: 325ms	remaining: 640ms

In [ ]:
from sklearn.naive_bayes import BernoulliNB
model=BernoulliNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print ("Accuracy",accuracy_score(y_test,y_pred))

Accuracy 0.9206896551724137