<a href="https://colab.research.google.com/github/NATHAN-70/AI-ML/blob/main/FNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv('/content/personality_datasert (1).csv')
df

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,4.0,No,4.0,6.0,No,13.0,5.0,Extrovert
1,9.0,Yes,0.0,0.0,Yes,0.0,3.0,Introvert
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert
3,0.0,No,6.0,7.0,No,14.0,8.0,Extrovert
4,3.0,No,9.0,4.0,No,8.0,5.0,Extrovert
...,...,...,...,...,...,...,...,...
2895,3.0,No,7.0,6.0,No,6.0,6.0,Extrovert
2896,3.0,No,8.0,3.0,No,14.0,9.0,Extrovert
2897,4.0,Yes,1.0,1.0,Yes,4.0,0.0,Introvert
2898,11.0,Yes,1.0,3.0,Yes,2.0,0.0,Introvert
2899,3.0,No,6.0,6.0,No,6.0,9.0,Extrovert

In [ ]:
df.isnull().sum()

Time_spent_Alone             0
Stage_fear                   0
Social_event_attendance      0
Going_outside                0
Drained_after_socializing    0
Friends_circle_size          0
Post_frequency               0
Personality                  0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Time_spent_Alone           2900 non-null   float64
 1   Stage_fear                 2900 non-null   object
 2   Social_event_attendance    2900 non-null   float64
 3   Going_outside              2900 non-null   float64
 4   Drained_after_socializing  2900 non-null   object
 5   Friends_circle_size        2900 non-null   float64
 6   Post_frequency             2900 non-null   float64
 7   Personality                2900 non-null   object
dtypes: float64(5), object(3)
memory usage: 181.4+ KB

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
for i in df.columns:
  if df[i].dtype=='float64':
      df[i]=sc.fit_transform(df[[i]])
df

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,-0.147014,No,0.012759,1.350613,No,1.590680,0.496104,Extrovert
1,1.306226,Yes,-1.379944,-1.350613,Yes,-1.481437,-0.195199,Introvert
2,1.306226,Yes,-1.031768,-0.450204,Yes,-0.299853,-0.540850,Introvert
3,-1.309607,No,0.709111,1.800817,No,1.826996,1.533059,Extrovert
4,-0.437663,No,1.753638,0.450204,No,0.409096,0.496104,Extrovert
...,...,...,...,...,...,...,...,...
2895,-0.437663,No,1.057286,1.350613,No,-0.063537,0.841756,Extrovert
2896,-0.437663,No,1.405462,0.000000,No,1.826996,1.878710,Extrovert
2897,-0.147014,Yes,-1.031768,-0.900408,Yes,-0.536170,-1.232153,Introvert
2898,1.887522,Yes,-1.031768,0.000000,Yes,-1.008803,-1.232153,Introvert
2899,-0.437663,No,0.709111,1.350613,No,-0.063537,1.878710,Extrovert

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in df.columns:
  if df[i].dtype=='object':
      df[i]=le.fit_transform(df[[i]])
df

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,-0.147014,0,0.012759,1.350613,0,1.590680,0.496104,0
1,1.306226,1,-1.379944,-1.350613,1,-1.481437,-0.195199,1
2,1.306226,1,-1.031768,-0.450204,1,-0.299853,-0.540850,1
3,-1.309607,0,0.709111,1.800817,0,1.826996,1.533059,0
4,-0.437663,0,1.753638,0.450204,0,0.409096,0.496104,0
...,...,...,...,...,...,...,...,...
2895,-0.437663,0,1.057286,1.350613,0,-0.063537,0.841756,0
2896,-0.437663,0,1.405462,0.000000,0,1.826996,1.878710,0
2897,-0.147014,1,-1.031768,-0.900408,1,-0.536170,-1.232153,1
2898,1.887522,1,-1.031768,0.000000,1,-1.008803,-1.232153,1
2899,-0.437663,0,0.709111,1.350613,0,-0.063537,1.878710,0

In [ ]:
x=df.drop('Personality',axis=1)
y=df['Personality']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
#model defining
                       #hidden layer 1         #hidden layer 2               #output layer
model=Sequential([Dense(64,activation='relu'),Dense(32,activation='relu'),Dense(1,activation='sigmoid')])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
fnn=model.fit(x_train,y_train,epochs=100,batch_size=32,verbose=1)

Epoch 1/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8879 - loss: 0.3968
Epoch 2/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2693
Epoch 3/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9358 - loss: 0.2574
Epoch 4/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2499
Epoch 5/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9358 - loss: 0.2434
Epoch 6/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9358 - loss: 0.2382
Epoch 7/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2360
Epoch 8/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2309
Epoch 9/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2297
Epoch 10/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2264
Epoch 11/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2248
Epoch 12/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9353 - loss: 0.2224
Epoch 13/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2210
Epoch 14/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2191
Epoch 15/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2168
Epoch 16/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2156
Epoch 17/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2142
Epoch 18/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9353 - loss: 0.2132
Epoch 19/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9353 - loss: 0.2131
Epoch 20/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9353 - loss: 0.2118
Epoch 21/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9358 - loss: 0.2107
Epoch 22/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9358 - loss: 0.2099
Epoch 23/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9358 - loss: 0.2100
Epoch 24/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9358 - loss: 0.2102
Epoch 25/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2096
Epoch 26/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2092
Epoch 27/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9362 - loss: 0.2097
Epoch 28/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2101
Epoch 29/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2076
Epoch 30/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2054
Epoch 31/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9358 - loss: 0.2068
Epoch 32/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2072
Epoch 33/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2052
Epoch 34/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2036
Epoch 35/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9358 - loss: 0.2041
Epoch 36/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2046
Epoch 37/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2027
Epoch 38/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2033
Epoch 39/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2023
Epoch 40/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2019
Epoch 41/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2022
Epoch 42/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2025
Epoch 43/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2020
Epoch 44/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9358 - loss: 0.1993
Epoch 45/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2006
Epoch 46/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.2026
Epoch 47/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9362 - loss: 0.2002
Epoch 48/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1999
Epoch 49/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2000
Epoch 50/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2007
Epoch 51/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1994
Epoch 52/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.1997
Epoch 53/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.1979
Epoch 54/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2002
Epoch 55/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.2000
Epoch 56/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.1983
Epoch 57/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.1970
Epoch 58/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1974
Epoch 59/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1973
Epoch 60/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.1992
Epoch 61/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9353 - loss: 0.1983
Epoch 62/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1975
Epoch 63/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1970
Epoch 64/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1952
Epoch 65/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1970
Epoch 66/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1952
Epoch 67/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1951
Epoch 68/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9349 - loss: 0.1978
Epoch 69/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9358 - loss: 0.1956
Epoch 70/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9358 - loss: 0.1961
Epoch 71/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9353 - loss: 0.1940
Epoch 72/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9358 - loss: 0.1939
Epoch 73/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1950
Epoch 74/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1966
Epoch 75/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.1936
Epoch 76/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1962
Epoch 77/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1931
Epoch 78/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9358 - loss: 0.1947
Epoch 79/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1921
Epoch 80/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1917
Epoch 81/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1950
Epoch 82/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1929
Epoch 83/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1920
Epoch 84/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1937
Epoch 85/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9358 - loss: 0.1908
Epoch 86/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.1910
Epoch 87/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1923
Epoch 88/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9358 - loss: 0.1919
Epoch 89/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1902
Epoch 90/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9349 - loss: 0.1905
Epoch 91/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1910
Epoch 92/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1905
Epoch 93/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9358 - loss: 0.1896
Epoch 94/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1916
Epoch 95/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9353 - loss: 0.1887
Epoch 96/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9358 - loss: 0.1894
Epoch 97/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9353 - loss: 0.1900
Epoch 98/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9358 - loss: 0.1904
Epoch 99/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9349 - loss: 0.1898
Epoch 100/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9362 - loss: 0.1903

In [ ]:
y_pred=model.predict(x_test)
y_pred

19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

array([[9.89666522e-01],
       [3.57157774e-02],
       [9.40685511e-01],
       [7.53880143e-01],
       [8.25422704e-01],
       [7.47516572e-01],
       [9.86123681e-01],
       [1.23335108e-01],
       [9.73986924e-01],
       [9.62611198e-01],
       [2.05636751e-02],
       [2.25360822e-02],
       [9.90534842e-01],
       [8.77757728e-01],
       [3.38874734e-03],
       [9.58492994e-01],
       [7.42704630e-01],
       [1.47114038e-01],
       [1.16752239e-03],
       [9.62493658e-01],
       [3.36721237e-03],
       [8.21078658e-01],
       [8.92653465e-01],
       [6.07274920e-02],
       [2.19806936e-02],
       [9.76004183e-01],
       [9.58062053e-01],
       [8.87167633e-01],
       [8.44720006e-01],
       [3.29177007e-02],
       [3.90775641e-03],
       [2.71781792e-05],
       [7.20277846e-01],
       [9.39750493e-01],
       [9.80246842e-01],
       [1.19253038e-03],
       [5.55205625e-04],
       [7.17447547e-05],
       [3.55185390e-01],
       [9.93822694e-01],
       [3.69940326e-02],
       [1.39349420e-03],
       [9.30313706e-01],
       [9.67311680e-01],
       [5.51945344e-02],
       [7.48806715e-01],
       [8.00350606e-01],
       [8.73936653e-01],
       [4.56852689e-02],
       [5.71969291e-03],
       [1.75416898e-02],
       [2.62091111e-04],
       [2.20837206e-01],
       [7.42643595e-01],
       [3.14418152e-02],
       [9.62211132e-01],
       [4.43523843e-03],
       [3.43223885e-02],
       [7.76953548e-02],
       [8.47068608e-01],
       [2.77175149e-03],
       [8.41338485e-02],
       [9.69239533e-01],
       [7.82413483e-01],
       [9.95109558e-01],
       [9.55052793e-01],
       [1.60503027e-03],
       [1.42382924e-02],
       [2.91001853e-02],
       [9.65315461e-01],
       [9.54326630e-01],
       [1.29497878e-03],
       [1.59294736e-02],
       [9.93180647e-02],
       [9.99549270e-01],
       [1.11541986e-01],
       [9.96497929e-01],
       [9.26988780e-01],
       [3.92946554e-03],
       [9.43877459e-01],
       [1.45681691e-03],
       [1.40225813e-02],
       [9.83490050e-03],
       [8.03211868e-01],
       [6.19988795e-03],
       [9.81967688e-01],
       [8.72034609e-01],
       [2.57851202e-02],
       [4.97837225e-03],
       [9.92259562e-01],
       [9.32361305e-01],
       [1.11523174e-01],
       [7.96195306e-03],
       [2.59486556e-01],
       [1.84651918e-03],
       [9.95494664e-01],
       [1.12772457e-01],
       [7.73857176e-01],
       [9.06176746e-01],
       [9.85427976e-01],
       [9.17578161e-01],
       [1.96898487e-04],
       [7.26634113e-04],
       [9.06939507e-01],
       [1.84457768e-02],
       [9.96895790e-01],
       [9.36670244e-01],
       [1.68858108e-03],
       [5.73916882e-02],
       [9.95899737e-02],
       [1.69448536e-02],
       [1.47237659e-01],
       [3.30001046e-03],
       [8.76857996e-01],
       [1.81700140e-02],
       [9.36096072e-01],
       [6.72280714e-02],
       [9.14014637e-01],
       [7.11948812e-01],
       [9.63693440e-01],
       [1.33749489e-02],
       [9.86280501e-01],
       [1.06108133e-02],
       [9.91286755e-01],
       [9.52913821e-01],
       [2.44399123e-02],
       [1.04970299e-03],
       [8.60325992e-02],
       [9.91310775e-01],
       [5.16128652e-02],
       [6.85738574e-04],
       [9.70389426e-01],
       [2.16370672e-01],
       [9.42400336e-01],
       [9.61400092e-01],
       [9.81390774e-01],
       [9.86283302e-01],
       [9.63294983e-01],
       [1.52972518e-02],
       [7.98101164e-03],
       [9.81914163e-01],
       [2.42340029e-04],
       [7.74248362e-01],
       [5.74986963e-03],
       [8.32238495e-01],
       [9.17114139e-01],
       [1.22328324e-03],
       [1.74480736e-01],
       [4.71188221e-03],
       [8.75094950e-01],
       [6.36180863e-04],
       [2.57316224e-05],
       [7.35337555e-01],
       [9.97027218e-01],
       [3.07716000e-05],
       [9.58245218e-01],
       [2.28846772e-03],
       [2.32082810e-02],
       [2.39466038e-03],
       [4.21535131e-03],
       [1.40255630e-01],
       [9.91907954e-01],
       [9.88768756e-01],
       [8.46042037e-01],
       [3.29914659e-01],
       [7.92824268e-01],
       [9.54857051e-01],
       [5.34320949e-03],
       [7.06958473e-01],
       [2.13478059e-02],
       [9.50627983e-01],
       [1.50587608e-03],
       [9.78165388e-01],
       [3.57390530e-02],
       [3.23654339e-02],
       [9.83085692e-01],
       [1.47472024e-01],
       [9.51257408e-01],
       [9.25638199e-01],
       [9.75186646e-01],
       [4.88060601e-02],
       [9.95746672e-01],
       [9.80999291e-01],
       [1.17853239e-01],
       [9.97767448e-01],
       [6.85793936e-01],
       [5.67063596e-03],
       [8.76378894e-01],
       [9.86659110e-01],
       [9.77341235e-01],
       [7.40424450e-03],
       [3.29003520e-02],
       [9.94728148e-01],
       [1.87014304e-02],
       [9.24563825e-01],
       [9.56591308e-01],
       [8.58698249e-01],
       [8.62324703e-03],
       [3.12869787e-01],
       [9.19347465e-01],
       [2.94975843e-02],
       [3.85874629e-01],
       [9.81119692e-01],
       [9.98808622e-01],
       [8.38429406e-02],
       [7.87985504e-01],
       [3.21294628e-02],
       [2.41667658e-04],
       [1.70245871e-01],
       [9.45063233e-01],
       [2.31227884e-03],
       [8.39471936e-01],
       [1.70542881e-01],
       [7.84271598e-01],
       [4.75215614e-02],
       [2.09831521e-02],
       [8.43484402e-01],
       [8.89485423e-03],
       [9.81925666e-01],
       [9.89763796e-01],
       [8.07521582e-01],
       [1.52972518e-02],
       [1.56473592e-01],
       [9.09048438e-01],
       [1.03800884e-03],
       [2.42448553e-01],
       [1.02180894e-03],
       [5.72990440e-02],
       [4.19161357e-02],
       [9.34879720e-01],
       [7.37560913e-02],
       [1.23488486e-01],
       [9.32722986e-01],
       [8.20836276e-02],
       [3.13150929e-04],
       [6.80256248e-01],
       [9.73260343e-01],
       [4.56065452e-03],
       [4.26242361e-03],
       [1.06380285e-04],
       [9.95567262e-01],
       [3.33547801e-01],
       [6.01483434e-02],
       [9.10961270e-01],
       [2.94091199e-02],
       [9.41325903e-01],
       [9.96747851e-01],
       [7.75958955e-01],
       [1.64439101e-02],
       [8.19943309e-01],
       [9.97541368e-01],
       [8.94795597e-01],
       [1.06907531e-03],
       [9.16596472e-01],
       [9.19760883e-01],
       [9.37075973e-01],
       [2.89763529e-02],
       [9.84920979e-01],
       [1.71737205e-02],
       [8.16220522e-01],
       [3.54369655e-02],
       [9.82067227e-01],
       [2.24647149e-02],
       [9.24286306e-01],
       [8.56871665e-01],
       [4.39577503e-03],
       [7.05776364e-02],
       [2.28752643e-02],
       [9.59270179e-01],
       [5.59737273e-02],
       [3.30353491e-02],
       [2.53796011e-01],
       [7.68054783e-01],
       [1.89539790e-03],
       [1.70101643e-01],
       [6.45212177e-03],
       [9.44898275e-05],
       [3.43789397e-05],
       [1.33913187e-02],
       [1.27540216e-01],
       [7.29865283e-02],
       [6.70904279e-01],
       [9.79236066e-01],
       [7.03114793e-02],
       [9.66250062e-01],
       [9.95670557e-01],
       [9.56214488e-01],
       [4.23281789e-02],
       [9.76039350e-01],
       [7.90153027e-01],
       [2.87133530e-02],
       [7.81967878e-01],
       [5.64294755e-02],
       [8.68890941e-01],
       [8.30621123e-01],
       [9.34223652e-01],
       [3.28268943e-04],
       [2.97065116e-02],
       [3.38718630e-02],
       [9.77805793e-01],
       [2.23964057e-03],
       [2.44726855e-02],
       [4.80796397e-02],
       [7.65555263e-01],
       [7.46022999e-01],
       [7.98830211e-01],
       [1.44353779e-02],
       [5.12429141e-02],
       [2.20738828e-01],
       [9.91156280e-01],
       [1.50646176e-02],
       [2.38431748e-02],
       [1.36632919e-01],
       [9.73033965e-01],
       [8.37587893e-01],
       [5.52114248e-02],
       [2.42262632e-01],
       [8.71258974e-01],
       [1.83149531e-01],
       [7.73857176e-01],
       [2.22996925e-03],
       [9.94164169e-01],
       [4.48257774e-02],
       [1.67539082e-02],
       [8.49291682e-02],
       [9.48494911e-01],
       [9.94496524e-01],
       [9.79726732e-01],
       [1.54610779e-02],
       [1.69448536e-02],
       [9.66972828e-01],
       [9.84022617e-01],
       [9.62751091e-01],
       [5.85167715e-03],
       [3.69580798e-02],
       [9.82063890e-01],
       [1.34860456e-01],
       [9.62678790e-01],
       [6.32415637e-02],
       [2.46283077e-02],
       [8.37587893e-01],
       [2.38391191e-01],
       [9.14320707e-01],
       [9.67105806e-01],
       [3.76343541e-02],
       [9.93321717e-01],
       [1.80196657e-03],
       [9.38335121e-01],
       [9.67828274e-01],
       [9.41203475e-01],
       [6.37088669e-03],
       [9.85055625e-01],
       [9.10486519e-01],
       [7.07092648e-03],
       [9.56591308e-01],
       [7.78812319e-02],
       [9.08063233e-01],
       [8.63740742e-01],
       [9.54426527e-01],
       [2.52380647e-04],
       [2.26081233e-03],
       [3.93335149e-03],
       [7.56638885e-01],
       [9.67450082e-01],
       [2.13954039e-02],
       [2.91271455e-04],
       [9.82567787e-01],
       [6.41210296e-04],
       [1.83236197e-01],
       [9.44840074e-01],
       [3.24741192e-03],
       [9.09363389e-01],
       [8.22970092e-01],
       [7.46022999e-01],
       [4.96327132e-03],
       [2.30954005e-03],
       [1.72043014e-02],
       [2.87133530e-02],
       [9.26882327e-01],
       [2.23176535e-02],
       [9.28687871e-01],
       [3.65874693e-02],
       [8.18681180e-01],
       [6.28486052e-02],
       [1.90080926e-02],
       [7.25676417e-02],
       [9.39517170e-02],
       [9.47581351e-01],
       [8.51509511e-01],
       [5.86018665e-04],
       [9.24516559e-01],
       [7.22688511e-02],
       [7.96917379e-02],
       [4.18893388e-03],
       [9.33281720e-01],
       [9.16559398e-01],
       [2.28559479e-01],
       [9.86546814e-01],
       [2.33853310e-01],
       [1.38303571e-04],
       [4.30215150e-02],
       [1.77043991e-03],
       [1.34264032e-04],
       [9.73986924e-01],
       [9.72258925e-01],
       [1.49961099e-01],
       [9.18076456e-01],
       [9.02351499e-01],
       [9.84040022e-01],
       [9.64353740e-01],
       [2.61365231e-02],
       [9.67905402e-01],
       [9.59887087e-01],
       [1.03570679e-02],
       [1.76337864e-02],
       [2.09438615e-02],
       [1.45343074e-04],
       [1.20905675e-01],
       [1.96229154e-03],
       [1.05026225e-02],
       [5.07344864e-03],
       [8.89822245e-01],
       [1.18023017e-02],
       [4.49176738e-03],
       [1.15030492e-03],
       [9.35752690e-01],
       [1.19645577e-02],
       [1.65900332e-03],
       [4.43188734e-02],
       [8.13568950e-01],
       [2.86788191e-03],
       [3.70893162e-03],
       [9.57476377e-01],
       [8.20110440e-01],
       [7.92824268e-01],
       [7.79266179e-01],
       [7.92824268e-01],
       [9.96326268e-01],
       [9.26025271e-01],
       [1.77454948e-02],
       [9.73207295e-01],
       [9.90743220e-01],
       [9.59887087e-01],
       [9.17508960e-01],
       [6.08269451e-03],
       [9.93232653e-02],
       [4.47510462e-03],
       [9.47146475e-01],
       [9.67403650e-01],
       [7.17366278e-01],
       [1.89972203e-02],
       [8.42874587e-01],
       [9.46384072e-01],
       [6.68903887e-01],
       [9.50455189e-01],
       [1.92764087e-03],
       [1.37144867e-02],
       [9.20414567e-01],
       [3.02391755e-03],
       [9.84323084e-01],
       [9.77007031e-01],
       [7.80917823e-01],
       [5.40965237e-02],
       [9.76437628e-01],
       [9.38847721e-01],
       [7.30238378e-01],
       [4.10810782e-04],
       [1.82534812e-03],
       [9.88138378e-01],
       [9.47389841e-01],
       [7.87985504e-01],
       [7.99598455e-01],
       [6.11477764e-03],
       [2.38870401e-02],
       [7.27329180e-02],
       [1.94460875e-03],
       [9.48960841e-01],
       [5.58597185e-02],
       [9.47689235e-01],
       [1.04785282e-02],
       [8.06329429e-01],
       [8.51272166e-01],
       [7.52884895e-02],
       [9.15600479e-01],
       [3.52898352e-02],
       [2.42870189e-02],
       [8.04906249e-01],
       [2.08950695e-02],
       [6.61422731e-04],
       [9.77562428e-01],
       [7.09156739e-04],
       [8.00350606e-01],
       [1.73973255e-02],
       [1.61679015e-01],
       [2.39220858e-01],
       [4.43273969e-02],
       [9.84686494e-01],
       [9.15020466e-01],
       [9.85830784e-01],
       [9.62615758e-03],
       [3.36402794e-03],
       [9.73190188e-01],
       [6.16429839e-03],
       [9.56233084e-01],
       [6.39100075e-02],
       [8.70679226e-03],
       [5.47499396e-03],
       [9.67006862e-01],
       [7.96411991e-01],
       [9.10603464e-01],
       [7.17366278e-01],
       [4.86140028e-02],
       [7.48773158e-01],
       [9.17577982e-01],
       [6.89148545e-01],
       [5.53256541e-04],
       [9.22616243e-01],
       [9.69384253e-01],
       [1.60337109e-02],
       [2.95298602e-02],
       [9.99659300e-01],
       [3.23276147e-02],
       [4.44733873e-02],
       [1.93621423e-02],
       [5.69588179e-03],
       [8.64802897e-01],
       [6.01435953e-04],
       [9.76729155e-01],
       [3.85912508e-02],
       [6.11134887e-01],
       [9.56899405e-01],
       [9.81213409e-04],
       [9.95981157e-01],
       [5.13712694e-05],
       [1.52853690e-03],
       [7.20277846e-01],
       [9.17578161e-01],
       [6.12634644e-02],
       [1.36022493e-01],
       [9.91168737e-01],
       [7.50679299e-02],
       [8.22970092e-01],
       [9.09238040e-01],
       [4.31938097e-03],
       [9.81145918e-01],
       [8.94205630e-01],
       [9.88036394e-01],
       [3.14279366e-03],
       [4.00982657e-03],
       [2.53966707e-03],
       [1.96358915e-02],
       [1.03297614e-01],
       [9.84866977e-01],
       [9.15794432e-01],
       [3.44025008e-02],
       [1.23010308e-01],
       [3.80436219e-02],
       [9.83424187e-01],
       [8.43934476e-01],
       [8.46042037e-01],
       [9.88572717e-01],
       [4.51330282e-03],
       [9.85560298e-01],
       [9.84446168e-01],
       [6.07209222e-04],
       [2.86968946e-01],
       [9.26142693e-01],
       [8.41956019e-01],
       [7.25676417e-02],
       [8.56615007e-01],
       [2.39104498e-03],
       [7.20212400e-01],
       [8.86177838e-01],
       [7.09566399e-02],
       [9.70761061e-01],
       [2.75686383e-02],
       [9.23471451e-01],
       [8.07842731e-01],
       [5.21721691e-03],
       [9.77223098e-01]], dtype=float32)