<a href="https://colab.research.google.com/github/NATHAN-70/AI-ML/blob/main/Grid_Search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/drug200.csv')
df

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [ ]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Sex']=le.fit_transform(df['Sex'])
df['Cholesterol']=le.fit_transform(df['Cholesterol'])
df['BP']=le.fit_transform(df['BP'])
df['Drug']=le.fit_transform(df['Drug'])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df[['Age','Na_to_K']]=sc.fit_transform(df[['Age','Na_to_K']])

In [ ]:
x=df.drop(["Drug"],axis=1)
y=df["Drug"]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from sklearn.model_selection import GridSearchCV
param_grid={
    'criterion':['gini','entropy','log_loss'],
    'splitter':['best','random'],
    'max_depth':[None,10,20,40,50],
}
grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=5,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [None, 10, 20, 40, 50],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=5)

In [ ]:
from sklearn.metrics import classification_report,f1_score
f=f1_score(y_test,grid.predict(x_test), average='weighted')
f

1.0