<a href="https://colab.research.google.com/github/NATHAN-70/AI-ML/blob/main/Random_forest_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("/content/employee_salary_dataset.csv")

In [ ]:
df.isnull().sum()

EmployeeID          0
Name                0
Department          0
Experience_Years    0
Education_Level     0
Age                 0
Gender              0
City                0
Monthly_Salary      0
dtype: int64

In [ ]:
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['Name']=le.fit_transform(df['Name'])
df['Department']=le.fit_transform(df['Department'])
df['Education_Level']=le.fit_transform(df['Education_Level'])
df['City']=le.fit_transform(df['City'])

In [ ]:
x=df.drop('Monthly_Salary',axis=1)
y=df['Monthly_Salary']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=50)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()
rf.fit(x_train,y_train)
dt=RandomForestRegressor()
dt.fit(x_train,y_train)

RandomForestRegressor()

In [ ]:
y_pred=rf.predict(x_test)
y_pred

array([87389.82, 95943.27, 93136.04, 74786.9 , 78722.67])

In [ ]:
from sklearn.metrics import r2_score
mse=r2_score(y_test,y_pred)
mse

0.20845972204369112