<a href="https://colab.research.google.com/github/NATHAN-70/AI-ML/blob/main/RFE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv('/content/kidney_disease_dataset.csv')
df

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,48,80,1.020,1,0,0,1,0,0,7800,...,44,7800,0,1,1,1,0,0,0,1
1,7,50,1.020,4,0,0,1,0,0,6000,...,38,6000,0,0,0,0,0,0,0,0
2,62,80,1.010,2,3,1,1,0,0,7500,...,31,7500,0,1,1,1,1,0,0,1
3,48,70,1.005,4,0,1,1,0,0,6700,...,32,6700,0,0,0,0,1,0,0,0
4,51,80,1.010,2,0,1,1,0,0,7300,...,35,7300,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55,80,1.020,0,0,1,1,0,0,6700,...,47,6700,0,0,0,0,0,0,0,0
396,42,70,1.025,0,0,1,1,0,0,7800,...,54,7800,0,1,1,1,0,0,0,1
397,12,80,1.020,0,0,1,1,0,0,6600,...,49,6600,0,0,0,0,0,0,0,0
398,17,60,1.025,0,0,1,1,0,0,7200,...,51,7200,0,0,0,0,0,0,0,0
399,58,80,1.025,0,0,1,1,0,0,6800,...,53,6800,0,0,0,0,0,0,0,0

In [ ]:
df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,48,80,1.020,1,0,0,1,0,0,7800,...,44,7800,0,1,1,1,0,0,0,1
1,7,50,1.020,4,0,0,1,0,0,6000,...,38,6000,0,0,0,0,0,0,0,0
2,62,80,1.010,2,3,1,1,0,0,7500,...,31,7500,0,1,1,1,1,0,0,1
3,48,70,1.005,4,0,1,1,0,0,6700,...,32,6700,0,0,0,0,1,0,0,0
4,51,80,1.010,2,0,1,1,0,0,7300,...,35,7300,0,0,0,0,0,0,0,0

In [ ]:
df.shape

(400, 25)

In [ ]:
df.isnull().sum()

age                0
bp                 0
sg                47
al                 0
su                 0
rbc                0
pc                 0
pcc                0
ba                 0
bgr                0
bu                 0
sc                17
sod                0
pot                0
hemo              52
pcv                0
wc                 0
rc                 0
htn                0
dm                 0
cad                0
appet              0
pe                 0
ane                0
classification     0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [ ]:
x=df.drop(['classification'],axis=1)
y=df['classification']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
rfe=RFE(estimator=model,n_features_to_select=15)
rfe.fit(x_train,y_train)
print("selected features:",rfe.support_)
print("feature ranking:",rfe.ranking_)

selected features: [False  True False False False False  True False  True  True False  True
  True False  True  True  True  True  True  True  True False  True  True]
feature ranking: [ 2  1  6  8  3 10  1  7  1  1  5  1  1  4  1  1  1  1  1  1  1  9  1  1]

In [ ]:
selected_features=x_train.columns[rfe.support_]
print(" 15 selected feature ")
for feature in selected_features:
  print(feature)

 15 selected feature
bp
pc
ba
bgr
sc
sod
hemo
pcv
wc
rc
htn
dm
cad
pe
ane